package com.careerorbit.service;
import com.careerorbit.ai.ChatGateway;import com.careerorbit.entity.*;import com.careerorbit.mapper.*;import com.careerorbit.security.CurrentUser;import com.fasterxml.jackson.databind.ObjectMapper;import org.junit.jupiter.api.*;import org.mockito.ArgumentCaptor;import org.springframework.data.redis.core.*;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.support.TransactionTemplate;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class InterviewServiceTest {
 private InterviewSessionMapper sessions;private InterviewAnswerMapper answers;private InterviewReportMapper reports;private QuestionGenerationService sets;private RagService rag;private ChatGateway chat;private CurrentUser current;private StringRedisTemplate redis;private ValueOperations<String,String> values;private ObjectMapper json;private InterviewSessionEntity session;private long answerId;
 @BeforeEach void setup(){sessions=mock(InterviewSessionMapper.class);answers=mock(InterviewAnswerMapper.class);reports=mock(InterviewReportMapper.class);sets=mock(QuestionGenerationService.class);rag=mock(RagService.class);chat=mock(ChatGateway.class);current=mock(CurrentUser.class);redis=mock(StringRedisTemplate.class);values=mock(ValueOperations.class);when(redis.opsForValue()).thenReturn(values);var user=new UserEntity();user.id=7L;when(current.require()).thenReturn(user);session=new InterviewSessionEntity();session.id="s";session.userId=7L;session.questionSetId=2L;session.status="IN_PROGRESS";session.currentQuestion=0;session.currentQuestionText="原题";session.questionType="BASE";session.followUpCount=0;when(sessions.selectById("s")).thenReturn(session);var set=new QuestionSetEntity();set.id=2L;set.userId=7L;set.questionsJson="[{\"question\":\"原题\"}]";when(sets.get(2L)).thenReturn(set);when(rag.search(anyString(),anyInt())).thenReturn(List.of());json=new ObjectMapper();answerId=8;doAnswer(i->{((InterviewAnswerEntity)i.getArgument(0)).id=++answerId;return 1;}).when(answers).insert(any(InterviewAnswerEntity.class));}
 private InterviewService service(){var tx=new TransactionTemplate(mock(PlatformTransactionManager.class));return new InterviewService(sessions,answers,reports,sets,rag,chat,current,redis,json,tx);}
 @Test void persistsAndScoresTwoConsecutiveFollowUpsAgainstActualQuestion(){var first=json.createObjectNode().put("overallScore",70).put("shouldFollowUp",true).put("followUpQuestion","追问一");var second=json.createObjectNode().put("overallScore",72).put("shouldFollowUp",true).put("followUpQuestion","追问二");var third=json.createObjectNode().put("overallScore",75).put("shouldFollowUp",true).put("followUpQuestion","不应出现");when(chat.json(anyString(),eq(com.fasterxml.jackson.databind.JsonNode.class))).thenReturn(first,second,third);var service=service();assertThat(service.answer("s","回答一").nextQuestion()).isEqualTo("追问一");assertThat(service.answer("s","回答二").nextQuestion()).isEqualTo("追问二");assertThat(service.answer("s","回答三").followUp()).isFalse();var prompts=ArgumentCaptor.forClass(String.class);verify(chat,times(3)).json(prompts.capture(),eq(com.fasterxml.jackson.databind.JsonNode.class));assertThat(prompts.getAllValues().get(0)).contains("原题");assertThat(prompts.getAllValues().get(1)).contains("追问一");assertThat(prompts.getAllValues().get(2)).contains("追问二");var saved=ArgumentCaptor.forClass(InterviewAnswerEntity.class);verify(answers,times(3)).insert(saved.capture());assertThat(saved.getAllValues()).extracting(a->a.questionType).containsExactly("BASE","FOLLOW_UP","FOLLOW_UP");assertThat(saved.getAllValues().get(1).parentAnswerId).isEqualTo(9L);assertThat(saved.getAllValues().get(2).parentAnswerId).isEqualTo(10L);}
 @Test void refreshRestoresFollowUpFromRedis(){var evaluation=json.createObjectNode().put("overallScore",70).put("shouldFollowUp",true).put("followUpQuestion","刷新后仍在的追问");when(chat.json(anyString(),eq(com.fasterxml.jackson.databind.JsonNode.class))).thenReturn(evaluation);var service=service();service.answer("s","回答");var cached=ArgumentCaptor.forClass(String.class);verify(values).set(eq("career:interview:s"),cached.capture(),eq(2L),eq(java.util.concurrent.TimeUnit.HOURS));when(values.get("career:interview:s")).thenReturn(cached.getValue());when(sessions.selectById("s")).thenReturn(null);assertThat(service.get("s").question()).isEqualTo("刷新后仍在的追问");assertThat(service.get("s").questionType()).isEqualTo("FOLLOW_UP");}
 @Test void duplicateReportGenerationReturnsPersistedReportWithoutCallingModel(){var existing=new InterviewReportEntity();existing.id=12L;existing.sessionId="s";when(reports.selectOne(any())).thenReturn(existing);assertThat(service().complete("s")).isSameAs(existing);verifyNoInteractions(chat);verify(answers,never()).selectList(any());}
}
