import{api,http}from'./http'
export type User={id:number;email:string;displayName:string;role:'USER'|'ADMIN';targetRole?:string}
export type Resume={id:number;userId:number;fileName:string;fileUrl:string;parsedJson:string;parentId?:number;sourceDiagnosisId?:number;sourceSuggestionId?:string;versionNo:number;createdAt:string}
export type Diagnosis={id:number;resumeId:number;resultJson:string;acceptedItemsJson:string;createdAt:string}
export type QuestionSet={id:number;title:string;jobTitle:string;questionsJson:string;createdAt:string}
export type Session={sessionId:string;targetRole:string;status:string;currentQuestion:number;followUpCount:number;totalQuestions:number;question?:string;questionType:'BASE'|'FOLLOW_UP';parentAnswerId?:number;startedAt:string}
export const authApi={login:(b:unknown)=>api<any>(http.post('/auth/login',b)),register:(b:unknown)=>api<any>(http.post('/auth/register',b)),me:()=>api<User>(http.get('/auth/me'))}
export const resumeApi={list:()=>api<Resume[]>(http.get('/resumes')),upload:(f:File)=>{const d=new FormData();d.append('file',f);return api<Resume>(http.post('/resumes',d))},get:(id:number)=>api<Resume>(http.get(`/resumes/${id}`)),diagnose:(id:number)=>api<Diagnosis>(http.post(`/resumes/${id}/diagnose`)),diagnosis:(id:number)=>api<Diagnosis|null>(http.get(`/resumes/${id}/diagnosis`)),version:(id:number,p:unknown)=>api<Resume>(http.post(`/resumes/${id}/versions`,p)),versions:(id:number)=>api<Resume[]>(http.get(`/resumes/${id}/versions`)),diff:(beforeId:number,afterId:number)=>api<any>(http.get('/resumes/versions/diff',{params:{beforeId,afterId}})),accept:(diagnosisId:number,suggestionId:string,parsed:unknown)=>api<{version:Resume;diagnosis:Diagnosis}>(http.post(`/resumes/diagnoses/${diagnosisId}/suggestions/${encodeURIComponent(suggestionId)}/accept`,parsed)),undo:(diagnosisId:number,suggestionId:string)=>api<Diagnosis>(http.delete(`/resumes/diagnoses/${diagnosisId}/suggestions/${encodeURIComponent(suggestionId)}/acceptance`))}
export const questionApi={list:()=>api<QuestionSet[]>(http.get('/question-sets')),generate:(b:unknown)=>api<QuestionSet>(http.post('/question-sets',b)),remove:(id:number)=>api<void>(http.delete(`/question-sets/${id}`))}
export const interviewApi={create:(questionSetId:number)=>api<Session>(http.post('/interviews',{questionSetId})),get:(id:string)=>api<Session>(http.get(`/interviews/${id}`)),history:()=>api<any[]>(http.get('/interviews')),answer:(id:string,answer:string)=>api<any>(http.post(`/interviews/${id}/answers`,{answer})),skip:(id:string)=>api<Session>(http.post(`/interviews/${id}/skip`)),complete:(id:string)=>api<any>(http.post(`/interviews/${id}/complete`)),report:(id:string)=>api<any>(http.get(`/interviews/${id}/report`)),streamQuestion}
export const dashboardApi={get:()=>api<any>(http.get('/dashboard'))}
export const imageApi={extractJd:(file:File)=>{const d=new FormData();d.append('file',file);return api<{text:string}>(http.post('/images/extract-jd',d))}}
export const knowledgeApi={list:()=>api<any[]>(http.get('/knowledge')),stats:()=>api<{documents:number;chunks:number}>(http.get('/knowledge/stats')),upload:(f:File,m:Record<string,unknown>)=>{const d=new FormData();d.append('file',f);Object.entries(m).forEach(([k,v])=>d.append(k,String(v)));return api<any>(http.post('/knowledge',d))},remove:(id:number)=>api<void>(http.delete(`/knowledge/${id}`)),reindex:(id:number)=>api<any>(http.post(`/knowledge/${id}/reindex`))}
export const adminApi={users:()=>api<User[]>(http.get('/admin/users')),calls:()=>api<any[]>(http.get('/admin/ai-calls')),model:()=>api<any>(http.get('/admin/model')),prompts:()=>api<any[]>(http.get('/admin/prompts')),savePrompt:(body:unknown)=>api<any>(http.post('/admin/prompts',body)),deletePrompt:(id:number)=>api<void>(http.delete(`/admin/prompts/${id}`))}

async function streamQuestion(id:string,onDelta:(delta:string)=>void,signal?:AbortSignal){
 const token=localStorage.getItem('career_token');const response=await fetch(`/api/interviews/${encodeURIComponent(id)}/question-stream`,{headers:token?{Authorization:`Bearer ${token}`}:{},signal});
 if(!response.ok||!response.body)throw new Error(`流式提问失败（HTTP ${response.status}）`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
 const consume=(block:string)=>{let event='message';const data:string[]=[];for(const line of block.split('\n')){if(line.startsWith('event:'))event=line.slice(6).trim();if(line.startsWith('data:'))data.push(line.slice(5).trimStart())}const value=data.join('\n');if(event==='delta')onDelta(value);if(event==='error')throw new Error(value||'模型流式输出失败');return event==='done'};
 while(true){const{done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done}).replace(/\r/g,'');let split;while((split=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,split);buffer=buffer.slice(split+2);if(consume(block)){await reader.cancel();return}}if(done)break}
 if(buffer.trim())consume(buffer)
}
