<script setup lang="ts">
import{onMounted,ref}from'vue';import{adminApi}from'../api/modules';import{ElMessage}from'element-plus';
const tab=ref<'status'|'users'|'logs'|'prompts'>('status'),users=ref<any[]>([]),logs=ref<any[]>([]),model=ref<any>(),prompts=ref<any[]>([]),error=ref(''),editing=ref<any>({promptKey:'',name:'',content:'',enabled:true});
async function load(){try{[users.value,logs.value,model.value,prompts.value]=await Promise.all([adminApi.users(),adminApi.calls(),adminApi.model(),adminApi.prompts()])}catch(e){error.value=(e as Error).message}}
async function save(){if(!editing.value.promptKey||!editing.value.name||!editing.value.content)return ElMessage.warning('请填写完整提示词');await adminApi.savePrompt(editing.value);prompts.value=await adminApi.prompts();editing.value={promptKey:'',name:'',content:'',enabled:true};ElMessage.success('提示词已保存')}
async function remove(id:number){await adminApi.deletePrompt(id);prompts.value=prompts.value.filter(p=>p.id!==id)}
onMounted(load)
</script>
<template><section class="page-head"><div><h2>管理控制台</h2><p>用户、独立模型网关、调用日志与提示词的真实运行视图。</p></div><router-link class="primary-button" to="/admin/knowledge"><el-icon><Collection/></el-icon>知识库管理</router-link></section><div v-if="error" class="error-box">{{error}}</div><nav class="admin-tabs"><button v-for="item in [['status','模型状态'],['users','用户列表'],['logs','AI 日志'],['prompts','提示词管理']]" :key="item[0]" :class="{active:tab===item[0]}" @click="tab=item[0] as any">{{item[1]}}</button></nav><section v-if="tab==='status'&&model" class="gateway-grid"><article v-for="(gateway,name) in model" :key="name" class="panel gateway-card"><div><span :class="['status-dot',{on:gateway.configured}]"/><small>{{String(name).toUpperCase()}} GATEWAY</small></div><h3>{{gateway.model}}</h3><p>{{gateway.baseUrl}}</p><b>{{gateway.configured?'已配置':'未配置'}}</b></article></section><section v-if="tab==='users'" class="panel admin-table"><div class="table-head"><span>用户</span><span>角色</span><span>目标岗位</span></div><div v-for="u in users" :key="u.id" class="table-row"><span><b>{{u.displayName}}</b><small>{{u.email}}</small></span><span class="tag" :class="u.role==='ADMIN'?'orange':'green'">{{u.role}}</span><span>{{u.targetRole||'未设置'}}</span></div></section><section v-if="tab==='logs'" class="panel admin-table"><div class="table-head logs"><span>网关 / 模型</span><span>操作</span><span>耗时</span><span>状态</span></div><div v-for="l in logs" :key="l.id" class="table-row logs"><span><b>{{l.provider}}</b><small>{{l.model}}</small></span><span>{{l.operation}}</span><span>{{l.latencyMs}} ms</span><span :class="l.success?'ok':'bad'">{{l.success?'成功':l.errorCode}}</span></div><div v-if="!logs.length" class="empty-inline">暂无调用日志</div></section><section v-if="tab==='prompts'" class="prompt-admin"><article class="panel prompt-form"><h3>{{editing.id?'编辑提示词':'新增提示词'}}</h3><input v-model="editing.promptKey" placeholder="唯一键，如 interview.followup"/><input v-model="editing.name" placeholder="显示名称"/><textarea v-model="editing.content" rows="12" placeholder="提示词正文"/><label><input v-model="editing.enabled" type="checkbox"/> 启用</label><button class="primary-button" @click="save">保存提示词</button></article><article class="prompt-list"><div v-for="p in prompts" :key="p.id" class="panel prompt-item"><div><span><b>{{p.name}}</b><small>{{p.promptKey}}</small></span><span class="tag" :class="p.enabled?'green':''">{{p.enabled?'启用':'停用'}}</span></div><p>{{p.content}}</p><footer><button @click="editing={...p}">编辑</button><button @click="remove(p.id)">删除</button></footer></div><div v-if="!prompts.length" class="state-card">暂无自定义提示词</div></article></section></template>
