<script setup lang="ts">
import{onBeforeUnmount,onMounted,ref}from'vue';import{useRoute,useRouter}from'vue-router';import{questionApi,interviewApi,type QuestionSet,type Session}from'../api/modules';import{ElMessage}from'element-plus';
const route=useRoute(),router=useRouter(),session=ref<Session>(),sets=ref<QuestionSet[]>([]),answer=ref(''),loading=ref(false),error=ref(''),streamError=ref(''),streamedQuestion=ref(''),streaming=ref(false),feedback=ref<any>(),citations=ref<any[]>([]);let streamController:AbortController|undefined;
async function load(){if(route.params.id){session.value=await interviewApi.get(String(route.params.id));startStream()}else sets.value=await questionApi.list()}
async function start(id:number){const s=await interviewApi.create(id);await router.replace(`/interview/${s.sessionId}`);session.value=s;startStream()}
function startStream(){streamController?.abort();streamedQuestion.value='';streamError.value='';if(!session.value?.question)return;const controller=new AbortController();streamController=controller;streaming.value=true;interviewApi.streamQuestion(session.value.sessionId,d=>streamedQuestion.value+=d,controller.signal).catch(e=>{if(e.name!=='AbortError')streamError.value=e.message}).finally(()=>{if(streamController===controller)streaming.value=false})}
async function submit(){if(!session.value||!answer.value.trim())return;streamController?.abort();loading.value=true;error.value='';try{const r=await interviewApi.answer(session.value.sessionId,answer.value);feedback.value=r.evaluation;citations.value=r.citations;answer.value='';session.value={...session.value,currentQuestion:r.questionIndex,followUpCount:r.followUpCount,question:r.nextQuestion,questionType:r.questionType,parentAnswerId:r.parentAnswerId};if(r.nextQuestion)startStream();else ElMessage.success('题目已完成，可以生成报告')}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function skip(){if(session.value){streamController?.abort();session.value=await interviewApi.skip(session.value.sessionId);startStream()}}
async function complete(){if(!session.value)return;streamController?.abort();loading.value=true;try{await interviewApi.complete(session.value.sessionId);router.push(`/report/${session.value.sessionId}`)}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
onMounted(()=>load().catch(e=>error.value=e.message));onBeforeUnmount(()=>streamController?.abort())
</script>
<template><section v-if="!session"><div class="page-head"><div><h2>模拟面试</h2><p>选择一份由真实 RAG 和模型生成的题目集开始。</p></div></div><div v-if="error" class="state-card error">{{error}}</div><div v-else-if="!sets.length" class="state-card">暂无题目集，请先前往“面试题生成”。</div><div class="card-grid"><article v-for="s in sets" :key="s.id" class="panel selectable-card"><el-icon><ChatDotRound/></el-icon><h3>{{s.title}}</h3><small>{{s.createdAt}}</small><button class="primary-button" @click="start(s.id)">开始面试</button></article></div></section><section v-else class="live-interview"><header class="panel interview-status"><span><i/>面试进行中</span><b>{{session.targetRole}}</b><em>{{session.currentQuestion+1}} / {{session.totalQuestions}} · {{session.questionType==='FOLLOW_UP'?'动态追问':'主问题'}} · 追问 {{session.followUpCount}} / 2</em></header><article class="panel qa-card"><small>AI 面试官 <i v-if="streaming" class="stream-pulse">实时生成中</i></small><h2>{{streamedQuestion||session.question||'本套题已完成'}}</h2><p v-if="streamError" class="stream-fallback">流式模型暂不可用，已显示持久化题目：{{streamError}}</p><template v-if="feedback"><div class="evaluation"><div><strong>{{feedback.overallScore}}</strong><span>本题得分</span></div><p>{{feedback.suggestions?.join('；')}}</p></div><details><summary>查看评分细则与参考答案</summary><pre>{{JSON.stringify(feedback,null,2)}}</pre></details><div class="citations"><b>RAG 引用来源</b><span v-for="c in citations" :key="c.chunkId">{{c.title}} · {{c.chunkId}}</span></div></template><textarea v-if="session.question" v-model="answer" rows="8" placeholder="输入真实回答，提交后将由 RAG + 模型评价"/><div v-if="error" class="error-box">{{error}}</div><div class="answer-actions"><button v-if="session.question" class="outline-button" @click="skip">跳过</button><button v-if="session.question" class="primary-button" :disabled="loading" @click="submit">{{loading?'评价中…':'提交回答'}}</button><button class="primary-button" :disabled="loading" @click="complete">结束并生成报告</button></div></article></section></template>
