<script setup lang="ts">
import{computed,onMounted,ref,watch}from'vue';import{useRoute}from'vue-router';import{resumeApi,type Resume,type Diagnosis}from'../api/modules';import{ElMessage}from'element-plus';
const route=useRoute(),resumes=ref<Resume[]>([]),resumeId=ref<number>(),diagnosis=ref<Diagnosis|null>(),versions=ref<Resume[]>([]),loading=ref(false),error=ref(''),diff=ref<any>();
const result=computed(()=>{try{return diagnosis.value?JSON.parse(diagnosis.value.resultJson):null}catch{return null}}),accepted=computed<string[]>(()=>{try{return diagnosis.value?JSON.parse(diagnosis.value.acceptedItemsJson||'[]'):[]}catch{return[]}}),current=computed(()=>resumes.value.find(r=>r.id===resumeId.value)||versions.value.find(r=>r.id===resumeId.value));
const suggestionId=(issue:any,i:number)=>String(issue.id??i);
async function load(){resumes.value=await resumeApi.list();resumeId.value=Number(route.query.resumeId)||resumes.value[0]?.id;if(resumeId.value)await loadResume(resumeId.value)}
async function loadResume(id:number){error.value='';diff.value=null;try{diagnosis.value=await resumeApi.diagnosis(id)}catch{diagnosis.value=null}versions.value=await resumeApi.versions(id)}
async function diagnose(){if(!resumeId.value)return;loading.value=true;error.value='';try{diagnosis.value=await resumeApi.diagnose(resumeId.value);ElMessage.success('模型诊断已保存')}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
function replaceDeep(node:any,from:string,to:string):boolean{if(!node||!from)return false;const target=from.trim();for(const k of Object.keys(node)){const v=node[k];if(typeof v==='string'&&v.trim()===target){node[k]=to;return true}if(v&&typeof v==='object'&&replaceDeep(v,from,to))return true}return false}
async function apply(issue:any,i:number){if(!current.value||!diagnosis.value)return;const parsed=JSON.parse(current.value.parsedJson);if(!replaceDeep(parsed,issue.original,issue.rewrite))return ElMessage.warning('原文位置已变化，请重新诊断');loading.value=true;try{const saved=await resumeApi.accept(diagnosis.value.id,suggestionId(issue,i),parsed);diagnosis.value=saved.diagnosis;resumes.value.unshift(saved.version);versions.value=await resumeApi.versions(saved.version.id);resumeId.value=saved.version.id;await showDiff(saved.version);ElMessage.success('采纳状态与新版本均已持久化')}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function undo(issue:any,i:number){if(!diagnosis.value)return;try{diagnosis.value=await resumeApi.undo(diagnosis.value.id,suggestionId(issue,i));ElMessage.success('已撤销采纳状态，历史版本仍保留')}catch(e){error.value=(e as Error).message}}
async function showDiff(version:Resume){if(!version.parentId){diff.value=null;return}diff.value=await resumeApi.diff(version.parentId,version.id)}
watch(resumeId,id=>{if(id)loadResume(id).catch(e=>error.value=e.message)})
onMounted(()=>load().catch(e=>error.value=e.message))
</script>
<template><section class="page-head"><div><h2>简历优化</h2><p>采纳、撤销、版本与差异均由后端持久化。</p></div><select v-model="resumeId"><option v-for="r in resumes" :key="r.id" :value="r.id">{{r.fileName}} · V{{r.versionNo}}</option></select></section><div v-if="!resumes.length" class="state-card">请先上传一份简历。</div><template v-else><div class="toolbar"><button class="primary-button" :disabled="loading" @click="diagnose"><el-icon><MagicStick/></el-icon>{{loading?'处理中…':'开始 AI 诊断'}}</button><span v-if="diagnosis">诊断 #{{diagnosis.id}} · 已采纳 {{accepted.length}} 项</span></div><div v-if="error" class="error-box">{{error}}</div><div class="version-strip panel"><b>版本树</b><button v-for="v in versions" :key="v.id" :class="{active:v.id===resumeId}" @click="resumeId=v.id;showDiff(v)">V{{v.versionNo}}<small v-if="v.sourceSuggestionId">建议 {{v.sourceSuggestionId}}</small></button></div><div v-if="diff" class="panel diff-panel"><div><small>优化前 · V{{diff.before.versionNo}}</small><pre>{{JSON.stringify(diff.beforeContent,null,2)}}</pre></div><div><small>优化后 · V{{diff.after.versionNo}}</small><pre>{{JSON.stringify(diff.afterContent,null,2)}}</pre></div></div><div v-if="result" class="diagnosis-layout"><article class="panel score-card"><small>综合评分</small><strong>{{result.overallScore}}</strong><div><span>完整性 <b>{{result.completenessScore}}</b></span><span>专业性 <b>{{result.professionalismScore}}</b></span><span>表达 <b>{{result.expressionScore}}</b></span></div></article><article class="issues"><div v-for="(issue,i) in result.issues" :key="issue.id||i" class="panel issue-card"><div><span class="tag orange">{{issue.section}} · {{issue.severity}}</span><button v-if="!accepted.includes(suggestionId(issue,Number(i)))" :disabled="loading" @click="apply(issue,Number(i))">采纳并保存版本</button><button v-else class="undo" @click="undo(issue,Number(i))">撤销采纳</button></div><h3>{{issue.suggestion}}</h3><small>原文</small><p>{{issue.original}}</p><small>建议改写</small><p class="rewrite">{{issue.rewrite}}</p><em>{{issue.reason}}</em></div></article></div><div v-else-if="!loading" class="state-card">尚无诊断结果，点击按钮调用模型。</div></template></template>
